// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Race.Repo.ApplicationContext;

namespace Race.Repo.Migrations
{
    [DbContext(typeof(RaceContext))]
    [Migration("20200811161159_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Race.Model.Models.Pilot", b =>
                {
                    b.Property<Guid>("PilotId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Nationality")
                        .IsRequired();

                    b.Property<string>("Number")
                        .IsRequired();

                    b.HasKey("PilotId");

                    b.ToTable("Pilots");

                    b.HasData(
                        new
                        {
                            PilotId = new Guid("595a50ec-75a6-434c-98f7-dc28a5ad6c00"),
                            Code = "HAM",
                            Name = "Lewis Hamilton",
                            Nationality = "British",
                            Number = "44"
                        },
                        new
                        {
                            PilotId = new Guid("c274f0f1-9aba-41ef-b271-e671074d8aa2"),
                            Code = "HEI",
                            Name = "Nick Heidfeld",
                            Nationality = "German",
                            Number = "50"
                        },
                        new
                        {
                            PilotId = new Guid("3dc612c0-5582-46ba-b2fa-6d72493e130d"),
                            Code = "ROS",
                            Name = "Nico Rosberg",
                            Nationality = "German",
                            Number = "6"
                        },
                        new
                        {
                            PilotId = new Guid("af592a6b-20f2-45eb-b942-b41b899dd887"),
                            Code = "RAI",
                            Name = "Kimi Raikonnen",
                            Nationality = "Finnish",
                            Number = "14"
                        },
                        new
                        {
                            PilotId = new Guid("f91f48d4-51ea-4f44-95ec-182b8e7b029c"),
                            Code = "KUB",
                            Name = "Robert Kubica",
                            Nationality = "Polish",
                            Number = "19"
                        },
                        new
                        {
                            PilotId = new Guid("6b63d3a4-8a19-41e1-b895-60ea9d501c0a"),
                            Code = "GLO",
                            Name = "Timo Glock",
                            Nationality = "German",
                            Number = "20"
                        },
                        new
                        {
                            PilotId = new Guid("a9e5ba71-62f9-49d6-977a-647bdd3b7037"),
                            Code = "SAT",
                            Name = "Tacuma Sato",
                            Nationality = "Japanese",
                            Number = "21"
                        },
                        new
                        {
                            PilotId = new Guid("aeb5a563-9b9f-44db-a56e-d7404ade9be3"),
                            Code = "MAS",
                            Name = "Felipe Massa",
                            Nationality = "Brazilian",
                            Number = "22"
                        },
                        new
                        {
                            PilotId = new Guid("918ad535-b482-40af-acb5-0219418b51fe"),
                            Code = "COU",
                            Name = "David Coulthard",
                            Nationality = "British",
                            Number = "23"
                        },
                        new
                        {
                            PilotId = new Guid("3f179e30-f470-4253-a90c-fdc5cef4f76e"),
                            Code = "TRU",
                            Name = "Jarno Trulli",
                            Nationality = "Italian",
                            Number = "24"
                        },
                        new
                        {
                            PilotId = new Guid("8e1b2be1-4a7c-4ec2-9072-a0ae97642605"),
                            Code = "SUT",
                            Name = "Adrian Sutil",
                            Nationality = "German",
                            Number = "25"
                        },
                        new
                        {
                            PilotId = new Guid("30e3c76b-106a-42af-880a-0e7a4b9d18e8"),
                            Code = "WEB",
                            Name = "Mark Webber",
                            Nationality = "Australian",
                            Number = "26"
                        },
                        new
                        {
                            PilotId = new Guid("76031f5a-3682-45ac-afac-8f31440cd863"),
                            Code = "ALO",
                            Name = "Alonso",
                            Nationality = "Spanish",
                            Number = "27"
                        },
                        new
                        {
                            PilotId = new Guid("649c17e2-1ff7-4ad4-853f-103d7a24d937"),
                            Code = "BUT",
                            Name = "Jenson Button",
                            Nationality = "British",
                            Number = "28"
                        },
                        new
                        {
                            PilotId = new Guid("5e76aee7-0b54-476b-9285-91eb98fe41a1"),
                            Code = "DAV",
                            Name = "Anthony Davidson",
                            Nationality = "British",
                            Number = "29"
                        },
                        new
                        {
                            PilotId = new Guid("c36e5c5a-355b-4f65-b6f3-814bba005eb9"),
                            Code = "VET",
                            Name = "Sebastian Vettel",
                            Nationality = "German",
                            Number = "30"
                        },
                        new
                        {
                            PilotId = new Guid("8c4750cb-a810-4344-a2ce-ed82a02a6cc1"),
                            Code = "FIS",
                            Name = "Giancarlo Fisichella",
                            Nationality = "Italian",
                            Number = "31"
                        },
                        new
                        {
                            PilotId = new Guid("265f95bd-189e-4286-9990-f6d212cb2bd5"),
                            Code = "BAR",
                            Name = "Rubens Barichello",
                            Nationality = "Brazilian",
                            Number = "32"
                        },
                        new
                        {
                            PilotId = new Guid("3ab659d6-8df9-40c6-abac-d5e26b1e3f56"),
                            Code = "SCH",
                            Name = "Michael Schumacher",
                            Nationality = "German",
                            Number = "33"
                        });
                });

            modelBuilder.Entity("Race.Model.Models.Result", b =>
                {
                    b.Property<Guid>("ResultId");

                    b.Property<Guid>("PilotId");

                    b.Property<int>("RaceId");

                    b.HasKey("ResultId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Race.Model.Models.Result", b =>
                {
                    b.HasOne("Race.Model.Models.Pilot", "Pilot")
                        .WithMany("Results")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
