// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Race.Repo.ApplicationContext;

namespace Race.Repo.Migrations
{
    [DbContext(typeof(RaceContext))]
    partial class RaceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Race.Model.Models.Pilot", b =>
                {
                    b.Property<Guid>("PilotId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Nationality")
                        .IsRequired();

                    b.Property<string>("Number")
                        .IsRequired();

                    b.HasKey("PilotId");

                    b.ToTable("Pilots");

                    b.HasData(
                        new
                        {
                            PilotId = new Guid("595a50ec-75a6-434c-98f7-dc28a5ad6c00"),
                            Code = "HAM",
                            Name = "Hamilton",
                            Nationality = "British",
                            Number = "44"
                        },
                        new
                        {
                            PilotId = new Guid("c274f0f1-9aba-41ef-b271-e671074d8aa2"),
                            Code = "HEI",
                            Name = "Heidfeld",
                            Nationality = "German",
                            Number = "50"
                        },
                        new
                        {
                            PilotId = new Guid("3dc612c0-5582-46ba-b2fa-6d72493e130d"),
                            Code = "ROS",
                            Name = "Rosberg",
                            Nationality = "German",
                            Number = "6"
                        },
                        new
                        {
                            PilotId = new Guid("76031f5a-3682-45ac-afac-8f31440cd863"),
                            Code = "ALO",
                            Name = "Alonso",
                            Nationality = "Spanish",
                            Number = "14"
                        });
                });

            modelBuilder.Entity("Race.Model.Models.Result", b =>
                {
                    b.Property<Guid>("ResultId");

                    b.Property<Guid>("PilotId");

                    b.Property<int>("RaceId");

                    b.HasKey("ResultId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Race.Model.Models.Result", b =>
                {
                    b.HasOne("Race.Model.Models.Pilot", "Pilot")
                        .WithMany("Results")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
