apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-management-service-deployment
spec:
  replicas: 2 # Run 2 instances for high availability
  selector:
    matchLabels:
      app: team-management-service
  template:
    metadata:
      labels:
        app: team-management-service
    spec:
      containers:
      - name: team-management-service
      # my resgistry: team-management
        image: team-management/team-management-service:v1 # The image you pushed
        ports:
        - containerPort: 8080 # The port exposed in your Dockerfile
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        # Best practice: Use Kubernetes Secrets for connection strings and other sensitive data
        # - name: ConnectionStrings__RaceConnection
        #   valueFrom:
        #     secretKeyRef:
        #       name: team-management-secrets
        #       key: db-connection-string