apiVersion: v1
kind: Service
metadata:
  name: team-management-service
spec:
  type: ClusterIP # Exposes the service on an internal IP in the cluster
  selector:
    app: team-management-service # This must match the labels in your Deployment
  ports:
  - protocol: TCP
    port: 80       # The port the service will be available on
    targetPort: 8080 # The port the container is listening on